// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class ActionTaken
{
    public int Id { get; set; }

    public string ActionTaken1 { get; set; }

    public string TableName { get; set; }
}