// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Aireport
{
    public int Id { get; set; }

    public int? Poid { get; set; }

    public int? Prid { get; set; }

    public string ControlNo { get; set; }

    public int? Risno { get; set; }

    public DateTime? Risdate { get; set; }

    public DateTime? Date { get; set; }

    public string PropertyInspector { get; set; }

    public string PropertyInspectorPosition { get; set; }

    public string PropertyInspector2 { get; set; }

    public string PropertyInspector2Position { get; set; }

    public string Pgsofficer { get; set; }

    public string PgsofficerPosition { get; set; }

    public string Head { get; set; }

    public string HeadPosition { get; set; }

    public string PreparedBy { get; set; }

    public string PropertyOfficer2 { get; set; }

    public string PropertyOfficerPosition2 { get; set; }

    public string NotedBy { get; set; }

    public string NotedByPosition { get; set; }

    public string PropertyOfficer { get; set; }

    public string PropertyOfficerPosition { get; set; }

    public virtual ICollection<Airdetail> Airdetails { get; set; } = new List<Airdetail>();

    public virtual PurchaseRequest Pr { get; set; }

    public virtual User PreparedByNavigation { get; set; }
}