// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Allotment
{
    public int Id { get; set; }

    public int? AppropriationId { get; set; }

    public DateTime? AllotmentDate { get; set; }

    public decimal? AllotmentAmount { get; set; }

    public string Remarks { get; set; }

    public DateTime? DateCreated { get; set; }

    public string CreatedB { get; set; }

    public virtual Appropriation Appropriation { get; set; }
}