// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class ColumnTitle
{
    public int Id { get; set; }

    public string ColumTitle { get; set; }

    public string AccountType { get; set; }
}