// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class ControlNumber
{
    public int Id { get; set; }

    public string ControlNo { get; set; }

    public int? OfficeId { get; set; }

    public string TableName { get; set; }

    public virtual Office Office { get; set; }
}