// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class DefaultAccount
{
    public int Id { get; set; }

    public string AccountCode { get; set; }

    public string AccountCodeText { get; set; }

    public string AccountName { get; set; }

    public string FundType { get; set; }

    public int? FundTypeId { get; set; }

    public virtual FundType FundTypeNavigation { get; set; }
}