// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string ExtName { get; set; }

    public string Position { get; set; }

    public string OfficeName { get; set; }

    public string OffcAcr { get; set; }

    public int? OfficeId { get; set; }

    public string Tin { get; set; }

    public string PagIbig { get; set; }

    public string PhilHealth { get; set; }

    public string Sss { get; set; }

    public string Status { get; set; }

    public string Salutation { get; set; }

    public string Sg { get; set; }

    public string Gsis { get; set; }

    public string SalaryGrade { get; set; }

    public string Steps { get; set; }

    public decimal? MonthlySalary { get; set; }

    public virtual ICollection<Bacmember> Bacmembers { get; set; } = new List<Bacmember>();

    public virtual ICollection<ItenaryofTravel> ItenaryofTravelApprovedByNavigations { get; set; } = new List<ItenaryofTravel>();

    public virtual ICollection<ItenaryofTravel> ItenaryofTravelEmployees { get; set; } = new List<ItenaryofTravel>();

    public virtual ICollection<Liquidation> Liquidations { get; set; } = new List<Liquidation>();

    public virtual Office Office { get; set; }

    public virtual ICollection<PayrollDetail> PayrollDetails { get; set; } = new List<PayrollDetail>();

    public virtual ICollection<PayrollDifferentialDetail> PayrollDifferentialDetails { get; set; } = new List<PayrollDifferentialDetail>();

    public virtual ICollection<PayrollOtdetail> PayrollOtdetails { get; set; } = new List<PayrollOtdetail>();

    public virtual ICollection<PayrollWageDetail> PayrollWageDetails { get; set; } = new List<PayrollWageDetail>();

    public virtual ICollection<Signatory> Signatories { get; set; } = new List<Signatory>();

    public virtual ICollection<Payee> Payees { get; set; } = new List<Payee>();
}