// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class File
{
    public int Id { get; set; }

    public int? RefId { get; set; }

    public string TableName { get; set; }

    public string Path { get; set; }

    public string RootFolder { get; set; }

    public string OriginalFileName { get; set; }

    public string CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}