// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Function
{
    public int Id { get; set; }

    public string Action { get; set; }

    public virtual ICollection<UserRole> Roles { get; set; } = new List<UserRole>();
}