// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Item
{
    public int Id { get; set; }

    public string Category { get; set; }

    public string Item1 { get; set; }

    public string Uom { get; set; }

    public decimal? Cost { get; set; }

    public DateTime? DateCreated { get; set; }

    public virtual ICollection<Prdetail> Prdetails { get; set; } = new List<Prdetail>();
}