// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Log
{
    public int Id { get; set; }

    public string TableName { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }

    public string Action { get; set; }

    public DateTime? DateCreated { get; set; }

    public string CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}