// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Lrdetail
{
    public int Id { get; set; }

    public int? Lrid { get; set; }

    public string Particulars { get; set; }

    public decimal? Amount { get; set; }

    public virtual Liquidation Lr { get; set; }
}