// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Ordetail
{
    public int Id { get; set; }

    public int? AppropriationId { get; set; }

    public int? ObligationId { get; set; }

    public string Particulars { get; set; }

    public decimal? Amount { get; set; }

    public decimal? AdjustedAmount { get; set; }

    public virtual Appropriation Appropriation { get; set; }

    public virtual Obligation Obligation { get; set; }
}