// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Payee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Office { get; set; }

    public string Address { get; set; }

    public string Note { get; set; }

    public int? OfficeId { get; set; }

    public virtual ICollection<Liquidation> Liquidations { get; set; } = new List<Liquidation>();

    public virtual ICollection<Obligation> Obligations { get; set; } = new List<Obligation>();

    public virtual Office OfficeNavigation { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}