// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Prdetail
{
    public int Id { get; set; }

    public int? Prid { get; set; }

    public int? ItemNo { get; set; }

    public decimal? Quantity { get; set; }

    public string Category { get; set; }

    public string Item { get; set; }

    public string Uom { get; set; }

    public decimal? Cost { get; set; }

    public decimal? TotalAmount { get; set; }

    public string TableName { get; set; }

    public int? ItemId { get; set; }

    public virtual Item ItemNavigation { get; set; }

    public virtual PurchaseRequest Pr { get; set; }
}