// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class PriceQuotation
{
    public int Id { get; set; }

    public int? Prid { get; set; }

    public DateTime? Date { get; set; }

    public string ControlNo { get; set; }

    public string Description { get; set; }

    public string Purpose { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Pgsofficer { get; set; }

    public string Position { get; set; }

    public string Office { get; set; }

    public virtual ICollection<Pqdetail> Pqdetails { get; set; } = new List<Pqdetail>();

    public virtual PurchaseRequest Pr { get; set; }
}