// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Province
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string SortOrder { get; set; }

    public virtual ICollection<Town> Towns { get; set; } = new List<Town>();
}