// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class SalarySchedule
{
    public int Id { get; set; }

    public string Sg { get; set; }

    public int? Step { get; set; }

    public decimal? Cost { get; set; }
}