// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Supplier
{
    public int Id { get; set; }

    public string SupplierName { get; set; }

    public string Address { get; set; }

    public string ContactNumber { get; set; }

    public string PhoneNumber { get; set; }

    public string FaxNumber { get; set; }

    public string CellNumber { get; set; }

    public bool? Status { get; set; }
}