// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Template
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string TemplateContent { get; set; }

    public string Type { get; set; }

    public int? OfficeId { get; set; }
}