// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class UnitOfMeasurement
{
    public int Id { get; set; }

    public string UnitOfMeasurement1 { get; set; }
}