// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class UserRole
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Function> Functions { get; set; } = new List<Function>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}