// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbSchema.Models;

public partial class Year
{
    public int Id { get; set; }

    public int? Year1 { get; set; }

    public bool? IsActive { get; set; }

    public int? OfficeId { get; set; }

    public virtual Office Office { get; set; }
}