// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroFinancing.DbFirst
{
    public partial class Customers
    {
        public long Id { get; set; }
    }
}